-- 조회수가 가장 많은 중고거래 게시판의 첨부파일 조회하기
-- https://school.programmers.co.kr/learn/courses/30/lessons/164671


-- WHERE MAX(B.VIEWS) 서브쿼리
SELECT CONCAT('/home/grep/src/', B.BOARD_ID, '/', F.FILE_ID, F.FILE_NAME, F.FILE_EXT) AS FILE_PATH
FROM USED_GOODS_BOARD B JOIN USED_GOODS_FILE F
ON B.BOARD_ID = F.BOARD_ID
WHERE (B.VIEWS) IN (
    SELECT MAX(B.VIEWS)
    FROM USED_GOODS_BOARD B
)
ORDER BY F.FILE_ID DESC


-- WHERE 절에서 조건 1개 + '=' -> LIMIT 사용가능
SELECT CONCAT('/home/grep/src/', B.BOARD_ID, '/', F.FILE_ID, F.FILE_NAME, F.FILE_EXT) AS FILE_PATH
FROM USED_GOODS_BOARD B JOIN USED_GOODS_FILE F
ON B.BOARD_ID = F.BOARD_ID
WHERE (B.BOARD_ID) = (
    SELECT BOARD_ID
    FROM USED_GOODS_BOARD B
    ORDER BY B.VIEWS DESC
    LIMIT 1
)
ORDER BY F.FILE_ID DESC


-- FROM MAX(B.VIEWS) -> TABLE C
SELECT CONCAT('/home/grep/src/', B.BOARD_ID, '/', F.FILE_ID, F.FILE_NAME, F.FILE_EXT) AS FILE_PATH
FROM (SELECT MAX(B.VIEWS) AS VIEWS FROM USED_GOODS_BOARD B) AS C, 
    USED_GOODS_BOARD B JOIN USED_GOODS_FILE F
ON B.BOARD_ID = F.BOARD_ID
WHERE C.VIEWS = B.VIEWS
ORDER BY F.FILE_ID DESC


-- '/home/grep/src/B.BOARD_ID/F.FILE_ID+F.FILE_NAME+F.FILE_EXT'
-- 서브쿼리 알아버림
-- 한나님 봉승님이 알려주심 짱짱맨